# Configurações para produção
spring.jpa.hibernate.ddl-auto=none

logging.level.org.hibernate.SQL=ERROR
logging.level.com.fatec.runetasks=WARN

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always