spring.application.name=runetasks
app.frontend.url=${FRONTEND_URL:http://localhost:3000}

# Logs
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
logging.level.org.springframework=INFO
logging.level.com.fatec.runetasks=INFO

# JPA configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Database configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/runetasksDB}
spring.datasource.username=${DB_USER:runetasksUSER}
spring.datasource.password=${DB_PASSWORD:RuneTasks-2026}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# SpringDoc configuration
springdoc.show-actuator=true
springdoc.override-with-generic-response=true

# JWT
jwt.secret=${JWT_SECRET:sua-chave-de-api-secreta-aqui}
jwt.expiration.ms=86400000